# Generated by Django 3.1.7 on 2021-03-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
